---
- name: EOS Show Commands
  hosts: all
  gather_facts: false
  connection: local

  vars:
    cli:
      host: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
      authorize: true
      transport: cli

  tasks:
    - name: eos show commands
      eos_command:
        commands:
          - show version
        provider: "{{ cli }}"
      register: output

    - name: show output
      debug:
        var: output